In [1]:
import pandas as pd

In [2]:
uploaded_file = "data/seoul_train.csv"

In [9]:
loaded_data = pd.read_csv(uploaded_file, encoding="cp949", header=0)  # CSV 파일 로드

In [11]:
with open(uploaded_file, encoding='cp949') as f:
    for _ in range(3):
        print(f.readline())

"사용월","호선명","지하철역","04시-05시 승차인원","04시-05시 하차인원","05시-06시 승차인원","05시-06시 하차인원","06시-07시 승차인원","06시-07시 하차인원","07시-08시 승차인원","07시-08시 하차인원","08시-09시 승차인원","08시-09시 하차인원","09시-10시 승차인원","09시-10시 하차인원","10시-11시 승차인원","10시-11시 하차인원","11시-12시 승차인원","11시-12시 하차인원","12시-13시 승차인원","12시-13시 하차인원","13시-14시 승차인원","13시-14시 하차인원","14시-15시 승차인원","14시-15시 하차인원","15시-16시 승차인원","15시-16시 하차인원","16시-17시 승차인원","16시-17시 하차인원","17시-18시 승차인원","17시-18시 하차인원","18시-19시 승차인원","18시-19시 하차인원","19시-20시 승차인원","19시-20시 하차인원","20시-21시 승차인원","20시-21시 하차인원","21시-22시 승차인원","21시-22시 하차인원","22시-23시 승차인원","22시-23시 하차인원","23시-24시 승차인원","23시-24시 하차인원","00시-01시 승차인원","00시-01시 하차인원","01시-02시 승차인원","01시-02시 하차인원","02시-03시 승차인원","02시-03시 하차인원","03시-04시 승차인원","03시-04시 하차인원","작업일자"

"202506","1호선","동대문","575","17","11259","1969","9299","7110","15607","12323","21635","19678","21319","22064","19129","25026","20255","28225","23988","26928","26118","25575","28197","24262","28180","23442","28497","22956","26927","22782","23966","22330","18091","21598","16795","16227","15038","14989","11277","14858","5887","9784","820","2982","0","236","0","0","0","0","20250703"

"202506","1호선","동묘앞","181","3","2690","925","3817","5502","8686","11267","13321","22446","12449","19629","14634","25320","20146","32284","26928","32663","33321","35208","33986","29758","33934","26263","34080","20690","30848","15644","22978","13310","12237","9607","6908","6486","5407","6857","3695","6654","1372","4739","115","1872","1","261","0","0","0","0","20250703"

In [10]:
loaded_data.head()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
0,202506,1호선,동대문,575,17,11259,1969,9299,7110,15607,...,9784,820,2982,0,236,0,0,0,0,20250703
1,202506,1호선,동묘앞,181,3,2690,925,3817,5502,8686,...,4739,115,1872,1,261,0,0,0,0,20250703
2,202506,1호선,서울역,730,49,10751,10048,29185,60086,90184,...,29968,4636,7575,5,178,0,0,0,0,20250703
3,202506,1호선,시청,96,0,1803,5796,3972,26490,7355,...,3737,538,983,0,12,0,0,0,0,20250703
4,202506,1호선,신설동,436,21,9189,2288,10160,8978,21468,...,9485,371,2857,0,0,0,0,0,0,20250703

In [18]:
loaded_data[loaded_data["작업일자"] == "20250603"]

Empty DataFrame
Columns: [사용월, 호선명, 지하철역, 04시-05시 승차인원, 04시-05시 하차인원, 05시-06시 승차인원, 05시-06시 하차인원, 06시-07시 승차인원, 06시-07시 하차인원, 07시-08시 승차인원, 07시-08시 하차인원, 08시-09시 승차인원, 08시-09시 하차인원, 09시-10시 승차인원, 09시-10시 하차인원, 10시-11시 승차인원, 10시-11시 하차인원, 11시-12시 승차인원, 11시-12시 하차인원, 12시-13시 승차인원, 12시-13시 하차인원, 13시-14시 승차인원, 13시-14시 하차인원, 14시-15시 승차인원, 14시-15시 하차인원, 15시-16시 승차인원, 15시-16시 하차인원, 16시-17시 승차인원, 16시-17시 하차인원, 17시-18시 승차인원, 17시-18시 하차인원, 18시-19시 승차인원, 18시-19시 하차인원, 19시-20시 승차인원, 19시-20시 하차인원, 20시-21시 승차인원, 20시-21시 하차인원, 21시-22시 승차인원, 21시-22시 하차인원, 22시-23시 승차인원, 22시-23시 하차인원, 23시-24시 승차인원, 23시-24시 하차인원, 00시-01시 승차인원, 00시-01시 하차인원, 01시-02시 승차인원, 01시-02시 하차인원, 02시-03시 승차인원, 02시-03시 하차인원, 03시-04시 승차인원, 03시-04시 하차인원, 작업일자]
Index: []

[0 rows x 52 columns]

In [14]:
loaded_data.tail()

,사용월,호선명,지하철역,04시-05시 승차인원,04시-05시 하차인원,05시-06시 승차인원,05시-06시 하차인원,06시-07시 승차인원,06시-07시 하차인원,07시-08시 승차인원,...,23시-24시 하차인원,00시-01시 승차인원,00시-01시 하차인원,01시-02시 승차인원,01시-02시 하차인원,02시-03시 승차인원,02시-03시 하차인원,03시-04시 승차인원,03시-04시 하차인원,작업일자
74894,201501,중앙선,운길산,0,0,177,56,642,403,1292,...,633,3,222,0,0,0,0,0,0,20151223
74895,201501,중앙선,원덕,1,0,292,4,415,46,537,...,383,3,157,0,0,0,0,0,0,20151223
74896,201501,중앙선,중랑,14,1,4929,424,8539,2084,22160,...,6501,86,1617,0,0,0,0,0,0,20151223
74897,201501,중앙선,팔당,0,0,161,50,368,149,1227,...,336,8,85,0,0,0,0,0,0,20151223
74898,201501,중앙선,회기,436,3,10929,3067,23317,10430,65043,...,35702,767,9314,0,0,0,0,0,0,20151223

In [13]:
", ".join(loaded_data.columns.tolist())

'사용월, 호선명, 지하철역, 04시-05시 승차인원, 04시-05시 하차인원, 05시-06시 승차인원, 05시-06시 하차인원, 06시-07시 승차인원, 06시-07시 하차인원, 07시-08시 승차인원, 07시-08시 하차인원, 08시-09시 승차인원, 08시-09시 하차인원, 09시-10시 승차인원, 09시-10시 하차인원, 10시-11시 승차인원, 10시-11시 하차인원, 11시-12시 승차인원, 11시-12시 하차인원, 12시-13시 승차인원, 12시-13시 하차인원, 13시-14시 승차인원, 13시-14시 하차인원, 14시-15시 승차인원, 14시-15시 하차인원, 15시-16시 승차인원, 15시-16시 하차인원, 16시-17시 승차인원, 16시-17시 하차인원, 17시-18시 승차인원, 17시-18시 하차인원, 18시-19시 승차인원, 18시-19시 하차인원, 19시-20시 승차인원, 19시-20시 하차인원, 20시-21시 승차인원, 20시-21시 하차인원, 21시-22시 승차인원, 21시-22시 하차인원, 22시-23시 승차인원, 22시-23시 하차인원, 23시-24시 승차인원, 23시-24시 하차인원, 00시-01시 승차인원, 00시-01시 하차인원, 01시-02시 승차인원, 01시-02시 하차인원, 02시-03시 승차인원, 02시-03시 하차인원, 03시-04시 승차인원, 03시-04시 하차인원, 작업일자'